---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: www/blog
  label: Posts
  create: all
  match: "**/*"
  exclude: images/*
  templates:
  - blog-post
upload_dir: www/uploads
public_path: "/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: vuepress build -d .vuepress/dist
  publish_command: vuepress build -d .vuepress/dist
  preview_env:
  - NODE_ENV=STAGE
  preview_output_directory: www/.dist
  output_directory: ".vuepress/dist"
  instant_preview_command: cd www & gridsome develop -p 8080 -h 0.0.0.0
  install_dependencies_command: npm --prefix www install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
