---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: posts
  label: Posts
  create: documents
  match: "**/*"
  templates:
  - blog-post
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
instant_preview: true
build:
  preview_env:
  - NODE_ENV=STAGE
  preview_output_directory: www/.dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv/www"
  instant_preview_command: npm run develop
  publish_command: vuepress build -d .vuepress/dist
  output_directory: ".vuepress/dist"
  preview_command: vuepress build -d .vuepress/dist
